export const GET_HOTELS_INFO = "GET_HOTELS_INFO";
export const GET_HOTELS_INFO_SUCCESS = "GET_HOTELS_INFO_SUCCESS";
export const GET_HOTELS_INFO_FAILED = "GET_HOTELS_INFO_FAILED";
export const HOTELS_INFO = "HOTELS_INFO";

export const ADD_FAVOURITE_HOTEL = "ADD_FAVOURITE_HOTEL";
export const REMOVE_FAVOURITE_HOTEL = "REMOVE_FAVOURITE_HOTEL";

export const SET_FAVOURITE_FILTER = "SET_FAVOURITE_FILTER";
