export const GET_HOTELS_INFO = "GET_HOTELS_INFO";
export const GET_HOTELS_INFO_SUCCESS = "GET_HOTELS_INFO_SUCCESS";
export const GET_HOTELS_INFO_FAILED = "GET_HOTELS_INFO_FAILED";
export const HOTELS_INFO = "HOTELS_INFO";
