import {
  GET_HOTELS_INFO,
  GET_HOTELS_INFO_SUCCESS,
  GET_HOTELS_INFO_FAILED,
  HOTELS_INFO,
  ADD_FAVOURITE_HOTEL,
  REMOVE_FAVOURITE_HOTEL,
  SET_FAVOURITE_FILTER,
} from "./hotels";

export {
  GET_HOTELS_INFO,
  GET_HOTELS_INFO_SUCCESS,
  GET_HOTELS_INFO_FAILED,
  HOTELS_INFO,
  ADD_FAVOURITE_HOTEL,
  REMOVE_FAVOURITE_HOTEL,
  SET_FAVOURITE_FILTER,
};
